baseURL = "https://jjermany.blog/"
enableRobotsTXT = "true"
languageCode = "ru-ru"
title = "üá©üá™ –ñ–∂—ë—Ä–º–∞–Ω–∏"
copyright = "¬© 2019. –°–¥–µ–ª–∞–ª —Å–∞–π—Ç –∏ –ø–∏—à–µ—Ç –ø–æ—Å—Ç—ã <a href='https://jarjan.xyz'>@jarjan</a>"
theme = "einfach-theme"
enableEmoji = true

[params]
  titleEmoji = "üá©üá™ –ñ–∂—ë—Ä–º–∞–Ω–∏"
  imageSrc = "https://jjermany.blog/jjermany.png"
  keywords = ["–±–ª–æ–≥", "–∞–π—Ç–∏", "–±–µ—Ä–ª–∏–Ω", "–≥–µ—Ä–º–∞–Ω–∏—è", "delivery hero"]
  description = "–ë–ª–æ–≥ –∞–π—Ç–∏—à–Ω–∏–∫–∞ –ø—Ä–æ –ì–µ—Ä–º–∞–Ω–∏—é"
  subtitle = "–∑–∞–º–µ—Ç–∫–∏ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Å—Ç–∞ –ø—Ä–æ –ë–µ—Ä–ª–∏–Ω –∏ –ì–µ—Ä–º–∞–Ω–∏—é"
  email = "zharzhan@gmail.com"
  twitter = "jarjan"
  sectionsOnIndex = ["post"]

[permalinks]
  posts = "/:slug/"