baseURL = "https://jjermany.blog/"
enableRobotsTXT = "true"
languageCode = "ru-ru"
title = "ğŸ‡©ğŸ‡ª Ğ–Ğ¶Ñ‘Ñ€Ğ¼Ğ°Ğ½Ğ¸"
theme = "hugo-theme-basic"

[params]
  subtitle = "Ğ·Ğ°Ğ¼ĞµÑ‚ĞºĞ¸ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼Ğ¼Ğ¸ÑÑ‚Ğ° Ğ¿Ñ€Ğ¾ Ğ‘ĞµÑ€Ğ»Ğ¸Ğ½ Ğ¸ Ğ“ĞµÑ€Ğ¼Ğ°Ğ½Ğ¸Ñ"
  email = "zharzhan@gmail.com"
  sectionsOnIndex = ["post"]

[permalinks]
  posts = "/:slug/"